name: dart_e_voting
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  # shared_preferences: ^2.3.2
  uuid: ^4.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
